version: "3"

networks:
  backend:
    driver: bridge

services:

#  worker:
#    build:
#      context: ./worker
#      args:
#        - http_proxy
#        - https_proxy
#        - no_proxy
#    env_file:
#      - ./.env
#    volumes:
#      - ~/.ssh:/root/.ssh
#      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
#    tty: true
#    networks:
#      - backend

  php-fpm:
    build:
      context: ./php-fpm
    env_file:
      - ./.env
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html${APP_CODE_CONTAINER_FLAG}
      - ./php-fpm/php7.4.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
      - "9501"
      - "9502"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    env_file:
      - ./.env
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    environment:
      - TZ=${TIMEZONE}
    networks:
      - backend
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    env_file:
      - ./.env
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    ports:
      - "${MYSQL_PORT}:3306"

  redis:
    build: ./redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
